
= Build with Docker

This section describes how to build {page-component-title} with Docker.

== Simple build

{page-component-title} can be compiled from source with a Docker build image:

. Check out the repository, compile the code, and install the plugin:
+
[source, console]
docker build -t myopennmshelmimage .

. Run the image:
+
[source, console]
docker run -p 3000:3000 -t myopennmshelmimage

. Log in to your {page-component-title} instance with the default admin credentials (`admin`/`admin`).
. Navigate to *Plugins* and enable the *OpenNMS Helm* plugin.

IMPORTANT: The Grafana plugin directory location is changed from `/var/lib/grafana/plugins` to `/opt/grafana/plugins`.
This is because the base Grafana image defines `/var/lib/grafana` as a volume, which cannot be changed.

== Advanced build

If you want to build a {page-component-title} image based on a specific GitHub fork or branch, you can use `--build-arg`:

[source, console]
----
docker build -t mycustomforkbranch \
            --build-arg OPENNMS_HELM_GIT_URL=https://github.com/OpenNMS/opennms-helm.git \
            --build-arg OPENNMS_HELM_GIT_BRANCH_REF=myBranch
----

This creates the plugin based on the GitHub URL and branch that you provide.

== Build service stack with Docker Compose

The {page-component-title} package includes an example `docker-compose.yml`, which builds a service stack with a compiled Grafana OpenNMS {page-component-title} plugin that you can test.
You can modify the build arguments in `docker-compose.yml` if you want to build from a specific GitHub fork, branch, or version tag.

When you first run `docker-compose up -d`, the Grafana {page-component-title} plugin is compiled from the source.
Subsequent runs will use the compiled image from your local system.
If you want to rebuild the image, run `docker-compose build --no-cache`.

The URL for your Horizon/Meridian datasource is `\http://opennms:8980/opennms`.

== Configure Docker for PDF reports

Horizon and Meridian include three templates from which you can create PDF reports.
They use an existing Grafana dashboard (see https://docs.opennms.com/horizon/31/operation/deep-dive/database-reports/templates/grafana.html[Grafana Dashboard] in the main OpenNMS documentation).
If you want to use this feature, and you are running {page-component-title} through Docker, you must complete additional configuration.
Refer to Grafana's https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service[Remote rendering service documentation] for more information.
Additional details are also available on https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md[GitHub].
