site:
  title: Grafana Plugin Documentation
  url: https://opennms-grafana-plugin-doc.netlify.com
  start_page: grafana-plugin::index.adoc
content:
  sources:
  - url: https://github.com/OpenNMS/grafana-plugin
    branches: develop
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    full-display-version: '12.0.0-SNAPSHOT'
    grafana-version-required: '12.x'
    grafana-version-tested: '12.0'
    node-js-build-version: '20.x'
    product-name: 'OpenNMS Plugin for Grafana'
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
