site:
  title: Grafana Plugin Documentation
  url: https://opennms-grafana-plugin-doc.netlify.com
  start_page: grafana-plugin::index.adoc
content:
  sources:
  - url: https://github.com/OpenNMS/grafana-plugin
    branches: release-9.x
    start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
asciidoc:
  attributes:
    experimental: true
    stem: latexmath
    full-display-version: '9.0.14-SNAPSHOT'
    grafana-version-required: '9.x'
    grafana-version-tested: '9.0'
    node-js-build-version: '16.x'
    product-name: 'OpenNMS Plugin for Grafana'
output:
  clean: true
  dir: ./public
  destinations:
  - provider: fs
  - provider: archive
