= Performance Datasource

== General

The _Performance Datasource_ can be used to retrieve performance metrics (i.e. data collection and/or response time metrics) from the _Measurements API_ in  OpenNMS.

The query editor provides the ability to build queries of the following types:

=== Attribute Queries

Used to extract data points from time series data that is collected and stored by OpenNMS.
The query is used to identify which attribute (or series) is being queried.

[options="header, autowidth"]
|===
| Name               | Description
| Node               | Node ID, or FS:FID (foreign source and foreign id) of the node to query.
| Resource           | Resource ID containing the requested attribute.
| Attribute          | Name of the attribute to query.
| Sub-Attribute      | Name of the sub-attribute to query.
                       This can be used to query metrics which are modeled using many datasources in a single RRD file (i.e. StrafePing).
| Fallback Attribute | Name of the attribute to query if the requested attribute was not available.
| Aggregation        | RRD aggregation to use when exporting the metrics.
                       Possible values are `Average`, `Min`, `Max` or `Last`.

| Label              | Name for the series.
                       Must be unique for all attributes and expression results in the query.
|===

=== Expression Queries

Used to combine or otherwise transform one or more series into a new series.
Supports mathematical and conditional operators provided by JEXL.
Consult the _Measurements API_ documentation of your _OpenNMS_ version for more details.

[options="header, autowidth"]
|===
| Name               | Description
| Expression         | JEXL expression
| Label              | Name for the series resulting from the expression.
|===

=== Filter Queries

Used to create new and/or alter existing series.

The option provided depend on the selected filter.

==== Outlier Filter

Used to remove datapoints from the series that fall outside of the configured quantile, defaults to 95%.
The datapoints are replaced with interpolated values.

== Template Queries

=== nodeFilter

The `nodeFilter()` query will return a list of nodes which match the given filter expression.

For example, to return the set of nodes that are in the `Production` and `Linux` categories, you can use:
```
nodeFilter(catincProduction & catincLinux)
```

=== nodeResources

The `nodeResources()` query will return the list of resource IDs  which are available on the given node.
Regular expressions in the template query can then be used to filter which resource IDs are used.

To query a specific node by id, you can use an expression similar to:
```
nodeResources(123)
```

To query a specific node by foreign source and foreign id, you can use an expression similar to:
```
nodeResources(FS:FID)
```
