[[helm-install-debian]]
= Install on Debian/Ubuntu

[IMPORTANT]
====
These instructions assume that you do not have https://grafana.com[Grafana] installed on the target system.
If you have an existing instance of https://grafana.com[Grafana] you would like to use, refer to xref:plugin.adoc#[Install via plugin].
====

== Install stable

Create a new apt source file (e.g,: /etc/apt/sources.list.d/opennms.list), and add the following two lines:

.Package repository configuration for Debian-based systems
[source, console]
----
deb https://debian.opennms.org stable main
deb-src https://debian.opennms.org stable main
----

Import the packages' authentication key with the following command:

.GPG key import for Debian-based systems
[source, console]
----
wget -O- https://debian.opennms.org/OPENNMS-GPG-KEY | tee -a /etc/apt/trusted.gpg.d/opennms.asc
----

Install the packages:

[source, console]
----
sudo apt-get update
sudo apt-get install opennms-helm
----

== Start the server (init.d service)

Start Grafana:

[source, console]
----
sudo service grafana-server start
----

This starts the grafana-server process as the grafana user, which is created during package installation. 

* Default HTTP port: 3000
* Default user and password: admin

To configure the Grafana server to start at boot time:

[source, console]
----
sudo /sbin/chkconfig --add grafana-server
----

== Start the server (via systemd)

[source, console]
----
sudo systemctl daemon-reload
sudo systemctl start grafana-server
sudo systemctl status grafana-server
----

To enable the systemd service to start at boot:

[source, console]
----
sudo systemctl enable grafana-server.service
----

== Next steps

xref:getting_started:index.adoc#[Set up your first dashboard].
