
= Install {page-component-title} Plugin

This section describes how to install the {page-component-title} plugin for Grafana.

IMPORTANT: These instructions assume that you already have Grafana installed on your target system.
If you do not have an existing Grafana instance, see xref:rpm.adoc[] or xref:debian.adoc[].

== Install via web UI

Follow these steps to install the {page-component-title} plugin using the Grafana UI:

. Navigate to your Grafana dashboard.
. Click the *Configuration* symbol and choose *Plugins*.
. Change the *State* to *All*.
. Search for "OpenNMS" and select the *OpenNMS Helm* plugin.
. Click *Install*.

== Install via CLI

You can the `grafana-cli` tool to install {page-component-title}:

[source, console]
grafana-cli plugins install opennms-helm-app

This installs the plugin in your Grafana plugins directory (default: `/var/lib/grafana/plugins`).
For more information on `grafana-cli`, see the http://docs.grafana.org/plugins/installation/[official Grafana documentation].

== Next steps

After you install the {page-component-title} plugin, you can xref:getting_started:index.adoc[create your first dashboard].
