
= Install on RPM-Based Linux

This section describes how to install {page-component-title} on RPM-based Linux distributions (CentOS, Fedora, openSUSE, RedHat).

IMPORTANT: These instructions assume that you do not have Grafana installed on your target system.
If you have an existing Grafana instance that you would like to use, see xref:plugin.adoc[].

== Install stable

Follow these steps to install the stable version of {page-component-title}:

. Install the package repository:
+
[source, console]
----
sudo yum install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel7.noarch.rpm
sudo rpm --import https://yum.opennms.org/OPENNMS-GPG-KEY
----

. Install the packages:
+
[source, console]
sudo yum install opennms-helm

== Start the Grafana server

You can start your Grafana server in two ways: using `init.d`, or using `systemd`.

=== init.d

Follow these steps to start your Grafana server using the `init.d` service:

. Start Grafana:
+
[source, console]
sudo service grafana-server start

** This starts the `grafana-server` process as the `grafana` user, which is created during package installation.
** Note that the default HTTP port and username/password combination are set to the following:
*** HTTP port: `3000`
*** Username/password: `admin`/`admin`

. Configure your Grafana server to start on boot:
+
[source, console]
sudo /sbin/chkconfig --add grafana-server

=== systemd

Follow these steps to start your Grafana server using `systemd`:

. Reload all daemons:
+
[source, console]
sudo systemctl daemon-reload

. Start the Grafana server and check its status:
+
[source, console]
----
sudo systemctl start grafana-server
sudo systemctl status grafana-server
----

. Configure the `systemd` service to start on boot:
+
[source, console]
sudo systemctl enable grafana-server.service

== Next steps

After you install Grafana and {page-component-title}, you can xref:getting_started:index.adoc[create your first dashboard].
