
= Install from Source

This section describes how to install the {page-component-title} from source.

IMPORTANT: These instructions assume that you already have Grafana installed on your target system.
If you do not have an existing Grafana instance, see xref:package.adoc[].

== Build the plugin

Follow these steps to build the plugin:

. Download the source tree into a subfolder called `opennms-helm-app` in Grafana's plugin directory:
+
[source, console]
----
mkdir -p /var/lib/grafana/plugins
cd /var/lib/grafana/plugins
git clone https://github.com/OpenNMS/opennms-helm.git opennms-helm-app
----

. Compile the plugin:
+
[source, console]
----
cd /var/lib/grafana/plugins/opennms-helm-app
npm install
npm run build
----

. Restart Grafana:
+
[source, console]
systemctl restart grafana-server

== Build Docker image

We use the following conventions for build arguments in this procedure:

* *GRAFANA_VERSION:* The version number for Grafana (default: `latest`).
* *OPENNMS_HELM_VERSION:* Used as a label in `org.opennms.helm.version` to identify the running plugin version.

Follow these steps to build a Docker image from source:

. Create a tarball artifact from the compiled source code:
+
[source, console]
----
mkdir -p ./artifacts
tar --exclude='.git' \
    --exclude='.circleci' \
    --exclude='./artifacts' \
    -czf "./artifacts/opennms-helm.tar.gz" .
----

. Build the Docker image and install the plugin from the tarball artifact:
+
[source, console]
----
docker build \
    --build-arg GRAFANA_VERSION=latest \
    --build-arg OPENNMS_HELM_VERSION=SNAPSHOT \
    -t myhelm:snapshot .
----

. Run Docker:
+
[source, console]
docker run -p 3000:3000 myhelm:snapshot

== Next steps

After you install Grafana and the plugin, you can xref:getting_started:index.adoc[create your first dashboard].
