
= Upgrade {page-component-title}

This section describes how to upgrade your {page-component-title} installation.
Usually, upgrading simply involves installing the new package.
Major version releases, however, can sometimes introduce breaking changes; in this case, upgrading may be more complex.

Before proceeding, make sure that you have installed the latest version of the {page-component-title}.
You should also have https://nodejs.org/[Node.js] installed.

== Upgrade datasources

Follow these steps to upgrade your datasources:

. Install https://github.com/grafana-wizzy/wizzy[Wizzy] and create a directory for your datasources:
+
[source, console]
----
npm i -g wizzy
mkdir /tmp/wizzy
cd /tmp/wizzy
----

. Configure Wizzy to communicate with your Grafana instance:
+
[source, console]
----
# create a local wizzy project directory
wizzy init
# configure Grafana login information
wizzy set grafana url http://localhost:3000
wizzy set grafana username admin
wizzy set grafana password admin
----

. Export your datasources to the Wizzy project directory:
+
[source, console]
wizzy import datasources

. Convert any `fault` datasources to `entity`:
+
[source, shell]
perl -pi -e 's/opennms-grafana-plugin-fault-datasource/opennms-grafana-plugin-entity-datasource/g' datasources/*.json

. Publish your changes to your Grafana instance:
+
[source, console]
wizzy export datasources
