= Entities Datasource

== General

Use the Entities Datasource to retrieve entity model objects from OpenNMS.
It currently supports alarms and nodes.

(For an example of the entities datasource in action, see xref:panel_configuration:dynamic-dashboard.adoc#pc-filter-panel[Creating a Filter Panel]).

== Datasource queries

The behavior of this datasource changes depending on which entity is chosen.
Attributes and values will change depending on the entity type.

NOTE: Currently the entities datasource only allows a single target.
Subsequent targets in the query editor will be ignored.

[[ds-entity-template]]
== Template queries

To change the behavior of a template query, you can pass a field name to the `attribute` field to use as the display value of the variable.

If no attribute argument is given, the query will return the `id` attribute of the entity.

The default if the `query` field is empty is `alarms()` (return a list of alarm IDs).

=== alarms([attribute])

The `alarms()` function queries the OpenNMS alarms REST API.

=== locations()

The `locations()` query returns a list of all available node locations.
Use this inside `nodeFilter()` to filter the number of nodes displayed by location.

.Example variable expression
* nodeFilter(location='Default')
* nodeFilter(location='$location')

=== nodeFilter(<filterQuery>)

The `nodeFilter()` query returns a list of nodes which match the given filter expression.

The filter expression must be an existing node attribute and its corresponding value.
The value can be a constant or a variable.

.Example
* nodeFilter(<node_attribute>='<value>')
* nodeFilter(location='Default')
* nodeFilter(location='$location')

=== nodes([attribute])

The `nodes()` function will query the OpenNMS node REST API to retrieve a list of unique values for a given attribute.
The result from this query can be used in a `nodeFilter()` query to filter nodes in either a Entity or Performance Datasource variable.
You can find a list of valid attributes from the `\http://HOSTNAME:8980/opennms/api/v2/nodes/properties` endpoint of your OpenNMS server.

.Example filtering nodes by the "region" asset record
. On your dashboard, create a variable called `region` and set the datasource to an Entity Datasource pointing to your server.
. Set the query to be `nodes(assetRecord.region)`.
. Save the variable and return to list of variables.
. Create a second variable called `node` and set the datasource to a Performance Datasource.
. Set the query to be `nodeFilter(region='$region')`.
. Save the variable and return to your dashboard.
. As you change the "region" variable, the options in the "node" variable should update to show only the matching nodes.
