= Entities datasource

== General

Use the _Entities Datasource_ to retrieve entity model objects from OpenNMS.
It currently supports alarms and nodes.

(For an example of the entities datasource in action, see xref:panel_configuration:dynamic-dashboard.adoc#pc-filter-panel[Creating a Filter Panel]).

== Datasource queries

The behavior of this datasource changes depending on which entity is chosen.
Attributes and values will change depending on the entity type.

NOTE: Currently the entities datasource only allows a single target.
Subsequent targets in the query editor will be ignored.

[[ds-entity-template]]
== Template queries

To change the behavior of a template query, you can pass a field name to the `attribute` field to use as the display value of the variable.

If no attribute argument is given, the query will return the `id` attribute of the entity.

The default if the `query` field is empty is `alarms()` (return a list of alarm IDs).

=== alarms([attribute])

The `alarms()` function queries the OpenNMS alarms REST API.

=== locations()

The `locations()` query returns a list of all available node locations. 
Use this inside `nodeFilter()` to filter the number of nodes displayed by location.

.Example variable expression
* nodeFilter(location='Default')
* nodeFilter(location='$location')

=== nodeFilter(<filterQuery>)

The `nodeFilter()` query returns a list of nodes which match the given filter expression.

The filter expression must be an existing node attribute and its corresponding value.
Separate multiple filter expressions with an '&' (<attribute1>=<value1> & <attribute2>=<value2> & ...).
The value can be a constant or a variable.

.Example
* nodeFilter(<node_attribute>='<value>')
* nodeFilter(location='Default')
* nodeFilter(location='$location')
* nodeFilter(location='$location' & label='localhost')

=== nodes([attribute])

The `nodes()` function will query the OpenNMS node ReST API.
