{
 "title": "Cortex Flow Deep Dive | OpenNMS Helm",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "flowds", "label": "FlowDataSource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "query_result(sum by (nodeId) (min_over_time(EXPORTER_INTERFACE[$__range])))"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "query_result(sum by (ifIndex) (min_over_time(EXPORTER_INTERFACE{nodeId=\"${node}\"}[$__range])))"
    }
   },
   {
    "name": "dscp",
    "label": "DSCP",
    "query": {
     "query": "query_result(sum by (dscp) (min_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"${node}\", ifIndex=\"${interface}\"}[$__range])))"
    }
   },
   { "name": "topk", "label": "TopK", "query": "3,5,10,15,20" }
  ]
 },
 "panels": [
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput by Application (TopK)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end())))",
     "legendFormat": "{{application}} (In)"
    },
    {
     "expr": "sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end())))",
     "legendFormat": "{{application}} (Out)"
    },
    {
     "expr": "(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30) - sum by () (sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end()))))",
     "legendFormat": "Other (In)"
    },
    {
     "expr": "(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30) - sum by () (sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end()))))",
     "legendFormat": "Other (Out)"
    }
   ]
  },
  {
   "title": "Data Usage by Application",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range])))) or label_replace(vector(0), \"application\", \"Other\", \"none\", \".*\")"
    },
    {
     "expr": "sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[$__range])) and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range]))) or label_replace(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[$__range])) - sum by () (sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\",direction=\"in\"}[$__range])) and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range])))), \"application\", \"Other\", \"none\", \".*\")"
    },
    {
     "expr": "sum by (application) (sum_over_time(BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[$__range])) and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range]))) or label_replace(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[$__range])) - sum by () (sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\",direction=\"out\"}[$__range])) and ignoring (direction) topk($topk, sum by (application) (sum_over_time (BY_TOS_AND_APP_${node}_${interface}{dscp=~\"$dscp\"}[$__range])))), \"application\", \"Other\", \"none\", \".*\")"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput by Host (TopK)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end())))",
       "legendFormat": "{{host}} (In)"
      },
      {
       "expr": "sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end())))",
       "legendFormat": "{{host}} (Out)"
      },
      {
       "expr": "(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30) - sum by () (sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end()))))",
       "legendFormat": "Other (In)"
      },
      {
       "expr": "(sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30) - sum by () (sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30 and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range] @ end()))))",
       "legendFormat": "Other (Out)"
      }
     ]
    },
    {
     "title": "Data Usage by Host",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "targets": [
      {
       "expr": "sort_desc(topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range]))) ) or label_replace(vector(0), \"host\", \"Other\", \"none\", \".*\")"
      },
      {
       "expr": "sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[$__range])) and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range]))) or label_replace(2 * sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[$__range])) - sum by () (sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"in\"}[$__range])) and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range])))), \"host\", \"Other\", \"none\", \".*\")"
      },
      {
       "expr": "sum by (host) (sum_over_time(BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[$__range])) and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range]))) or label_replace(2 * sum by () (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[$__range])) - sum by () (sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\", direction=\"out\"}[$__range])) and ignoring (direction) topk($topk, sum by (host) (sum_over_time (BY_TOS_AND_HOST_${node}_${interface}{dscp=~\"$dscp\"}[$__range])))), \"host\", \"Other\", \"none\", \".*\")"
      }
     ]
    }
   ]
  },
  {
   "title": "DSCPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput by DSCP",
     "type": "graph",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (dscp) (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[30s])) / 30",
       "legendFormat": "{{dscp}} (In)"
      },
      {
       "expr": "sum by (dscp) (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[30s])) / 30",
       "legendFormat": "{{dscp}} (Out)"
      }
     ]
    },
    {
     "title": "Data Usage by DSCP",
     "type": "table",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "sort_desc(sum by (dscp) (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\"}[$__range])))"
      },
      {
       "expr": "sum by (dscp) (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"in\"}[$__range]))"
      },
      {
       "expr": "sum by (dscp) (sum_over_time(EXPORTER_INTERFACE_TOS{nodeId=\"$node\", ifIndex=\"$interface\", dscp=~\"$dscp\", direction=\"out\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}