{
 "title": "Flow Deep Dive | OpenNMS Plugin for Grafana",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "flowds", "label": "Flow Datasource", "query": "opennms-flow-datasource" },
   { "name": "perfds", "label": "Perf. Datasource", "query": "opennms-performance-datasource" },
   { "name": "node", "label": "Node", "query": "exporterNodesWithFlows()" },
   {
    "name": "interface",
    "label": "Interface",
    "query": "interfacesOnExporterNodeWithFlows($node)"
   },
   {
    "name": "dscp",
    "label": "DSCP",
    "query": "dscpOnExporterNodeAndInterface($node, $interface, $__from, $__to)"
   }
  ]
 },
 "panels": [
  { "title": "Flow Interface Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput by Application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "functions": [
      {
       "name": "includeOther",
       "parameters": []
      },
      { "name": "topN", "parameters": [ "10" ] },
      { "name": "withExporterNode", "parameters": [ "$node" ] },
      { "name": "withIfIndex", "parameters": [ "$interface" ] },
      { "name": "withDscp", "parameters": [ "$dscp" ] },
      {
       "name": "perSecond",
       "parameters": []
      },
      {
       "name": "negativeEgress",
       "parameters": []
      }
     ],
     "interfaceId": "$interface",
     "metric": "applications",
     "nodeCriteria": "$node"
    }
   ]
  },
  {
   "title": "Data Usage by Application",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "functions": [
      { "name": "topN", "parameters": [ "10" ] },
      { "name": "withExporterNode", "parameters": [ "$node" ] },
      { "name": "withIfIndex", "parameters": [ "$interface" ] },
      { "name": "withDscp", "parameters": [ "$dscp" ] },
      {
       "name": "asTableSummary",
       "parameters": []
      }
     ],
     "metric": "applications"
    }
   ]
  },
  {
   "title": "SNMP Interface Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/sec" }
     ],
     "targets": [
      {
       "attribute": "ifHCInOctets",
       "fallbackAttribute": "ifInOctets",
       "label": "In",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      },
      {
       "attribute": "ifHCOutOctets",
       "fallbackAttribute": "ifOutOctets",
       "label": "Out",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      }
     ]
    },
    {
     "title": "Errors and Discards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 2 },
     "yaxes": [
      { "format": "none", "label": "packets/sec" }
     ],
     "targets": [
      {
       "aggregation": "MAX",
       "attribute": "ifInErrors",
       "label": "Errors In",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      },
      {
       "aggregation": "MAX",
       "attribute": "ifOutErrors",
       "label": "Errors Out",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      },
      {
       "aggregation": "MAX",
       "attribute": "ifInDiscards",
       "label": "Discards In",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      },
      {
       "aggregation": "MAX",
       "attribute": "ifOutDiscards",
       "label": "Discards Out",
       "nodeId": "$node",
       "resourceId": "interfaceSnmpByIfIndex[$interface]",
       "type": "attribute"
      }
     ]
    }
   ]
  },
  {
   "title": "Conversation (Flows)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput by Conversation (Top N)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/sec" }
     ],
     "targets": [
      {
       "functions": [
        { "name": "topN", "parameters": [ "10" ] },
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        {
         "name": "perSecond",
         "parameters": []
        },
        {
         "name": "negativeEgress",
         "parameters": []
        }
       ],
       "metric": "conversations"
      }
     ]
    },
    {
     "title": "Data Usage by Conversation (Top N)",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "functions": [
        { "name": "topN", "parameters": [ "10" ] },
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        {
         "name": "asTableSummary",
         "parameters": []
        }
       ],
       "metric": "conversations"
      }
     ]
    }
   ]
  },
  {
   "title": "Hosts (Flows)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput by Host (Top N)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/sec" }
     ],
     "targets": [
      {
       "functions": [
        { "name": "topN", "parameters": [ "10" ] },
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        {
         "name": "perSecond",
         "parameters": []
        },
        {
         "name": "negativeEgress",
         "parameters": []
        }
       ],
       "metric": "hosts"
      }
     ]
    },
    {
     "title": "Data Usage by Host (Top N)",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "functions": [
        { "name": "topN", "parameters": [ "10" ] },
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        {
         "name": "asTableSummary",
         "parameters": []
        }
       ],
       "metric": "hosts"
      }
     ]
    }
   ]
  },
  {
   "title": "DSCPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput by DSCP",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "Bps", "label": "bytes/sec" }
     ],
     "targets": [
      {
       "functions": [
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        {
         "name": "perSecond",
         "parameters": []
        },
        {
         "name": "negativeEgress",
         "parameters": []
        }
       ],
       "metric": "dscps"
      }
     ]
    },
    {
     "title": "Data Usage by DSCP",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "functions": [
        { "name": "withExporterNode", "parameters": [ "$node" ] },
        { "name": "withIfIndex", "parameters": [ "$interface" ] },
        { "name": "withDscp", "parameters": [ "$dscp" ] },
        {
         "name": "asTableSummary",
         "parameters": []
        }
       ],
       "metric": "dscps"
      }
     ]
    }
   ]
  }
 ]
}