= Installing on Debian / Ubuntu

[IMPORTANT]
====
These instructions assume that https://grafana.com[Grafana] is NOT already installed on the target system.
If you have an existing instance of https://grafana.com[Grafana] you would like to use, refer to xref:../installation/plugin.adoc#[Installing via plugin].
====

== Install stable

Create a new apt source file (eg: `/etc/apt/sources.list.d/opennms.list`), and add the following 2 lines:

.Package repository configuration for Debian-based systems
[source, shell]
----
deb https://debian.opennms.org stable main
deb-src https://debian.opennms.org stable main
----

Import the packages' authentication key with the following command:

.GPG key import for Debian-based systems
[source, shell]
----
wget -O - https://debian.opennms.org/OPENNMS-GPG-KEY | sudo apt-key add -
----

Install the packages:

[source, shell]
----
sudo apt-get update
sudo apt-get install opennms-helm
----

== Start the server (init.d service)

You can start Grafana by running:

[source, shell]
----
sudo service grafana-server start
----

This will start the `grafana-server` process as the `grafana` user,
which is created during package installation. The default HTTP port is
`3000`, and default user and group is `admin`.

To configure the Grafana server to start at boot time:

[source, shell]
----
sudo /sbin/chkconfig --add grafana-server
----

== Start the server (via systemd)

[source, shell]
----
sudo systemctl daemon-reload
sudo systemctl start grafana-server
sudo systemctl status grafana-server
----

=== Enable the systemd service to start at boot

[source, shell]
----
sudo systemctl enable grafana-server.service
----

== Next Steps

See xref:../getting_started/index.adoc#[Getting Started] for help in setting up your first dashboard.
