
= Contribute Code

You can contribute code to the {page-component-title} project via https://github.com/OpenNMS/opennms-helm[GitHub].
This section describes the codebase and how to prepare your development environment.

== Codebase

{page-component-title} development is done in the project's default GitHub branch (`develop`).
Commits are automatically compiled, tested, and merged to the `master` branch.
Releases are tagged from the `master` branch and submitted to the https://github.com/grafana/grafana-plugin-repository[Grafana plugin repository].

== Prepare development environment

Follow these steps to prepare your development environment:

. Download and install https://nodejs.org/en/download/[Node.js] and https://grafana.com/docs/grafana/latest/installation/[Grafana].
. Edit `grafana.ini` and configure it to allow unsigned plugin development:
+
[source, ini]
----
app_mode = development

...

[plugins]
allow_loading_unsigned_plugins = opennms-helm-app
----

. Use Git to check out the repository:
+
[source, console]
git clone https://github.com/OpenNMS/opennms-helm.git

. Navigate to your {page-component-title} directory:
+
[source, console]
cd opennnms-helm

. Install the build and runtime dependencies:
+
[source, console]
npm ci

. Build {page-component-title} to prime your `dist` directory:
+
[source, console]
npm run dev

. Symlink your `dist` directory to Grafana's plugin path:
+
[source, console]
ln -s /path/to/opennms-helm/dist /var/lib/grafana/plugins/opennms-helm-app

. Run a continuous build that watches for changes:
+
[source, console]
----
npm run watch
----
+
After you save a change to {page-component-title}, refresh Grafana to load the updates.
